# EMCAPI

networking:
  # IP the API will listen on
  host: 127.0.0.1

  # Port the API will listen on
  port: 8080

  # The URL path, for instance https://example.com/v3/aurora where aurora is the string written below, version numbers are always present
  url_path: aurora

behaviour:
  # The maximum entries a player can enter when looking up objects by name
  max_lookup_size: 100

  # Setting for testing reasons
  developer_mode: false
